#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reproduce TCM-QM manuscript Figures 1-5 from the frozen v5 release.

Every figure reads only from the frozen release under 02_数据冻结最新版_v5
(tables/ + audits/) and writes a PNG into 01_论文最新版_v6/figures_repro/. No
value is recomputed from scratch; all numbers are derived from the deposited
CSVs so a reviewer can regenerate each panel in a clean environment and check it
against the manuscript's Technical Validation section.

Figure 6 is generated by build_fig6_ml_readiness.py (Extra Trees mean +/- SD,
four targets); Figure 7 is a record-centred architecture schematic whose source
must be archived separately (it is not data-derived).

Usage:
    python build_figures.py            # rebuild all of Fig 1-5
    python build_figures.py fig2 fig3  # rebuild a subset
"""
from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import FancyBboxPatch

ROOT = Path(r"D:\Download\TCM-QM-项目总整合包_20260828\CURRENT")
DATA = ROOT / "02_数据冻结最新版_v5"
# Output to a separate directory so the hand-crafted paper figures in figures/
# are never overwritten. These regenerated panels carry identical numbers but
# are not pixel-identical to the authored figures.
FIGDIR = ROOT / "01_论文最新版_v6" / "figures_repro"
FIGDIR.mkdir(parents=True, exist_ok=True)

# Shared colour palette (teal primary + gold accent, consistent with Fig. 6).
TEAL = "#207070"
GOLD = "#D0A040"
GREY = "#8A8A8A"
INK = "#1a1a1a"

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 12,
    "axes.edgecolor": "#555555",
    "axes.linewidth": 1.0,
    "xtick.color": "#333333",
    "ytick.color": "#333333",
    "axes.spines.top": False,
    "axes.spines.right": False,
})


def load_master() -> pd.DataFrame:
    df = pd.read_csv(DATA / "tables" / "tcm_qm_master.csv", encoding="utf-8-sig", dtype={"cid": str})
    return df


def _num(series: pd.Series) -> np.ndarray:
    return pd.to_numeric(series, errors="coerce").dropna().to_numpy()


def parse_formula(formula: str) -> dict:
    """Hill-notation element count, e.g. 'C12H22O11' -> {'C':12,'H':22,'O':11}."""
    counts: dict = {}
    for el, n in re.findall(r"([A-Z][a-z]?)(\d*)", str(formula)):
        counts[el] = counts.get(el, 0) + (int(n) if n else 1)
    return counts


# --------------------------------------------------------------------------- #
# Figure 1 -- construction and selection evidence chain
# --------------------------------------------------------------------------- #
def fig1() -> None:
    flow = pd.read_csv(DATA / "tables" / "selection_flow_summary.csv", encoding="utf-8-sig")
    f = dict(zip(flow["step_id"], flow["record_count"]))
    n_cand = f["F0"]          # 6948
    n_cid = f["F0b"]          # 6106
    n_miss = f["F1"]          # 2860
    n_imag = f["F2"]          # 63
    n_noconv = f["F3"]        # 13
    n_qual = f["F4"]          # 4012
    n_dup = f["F5"]           # 816
    n_rel = f["F6"]           # 3196

    fig, ax = plt.subplots(figsize=(11, 5.2), dpi=200)
    ax.axis("off")
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)

    def box(x, y, w, h, title, sub, color):
        ax.add_patch(plt.Rectangle((x, y), w, h, facecolor=color, edgecolor="none", zorder=2))
        ax.text(x + w / 2, y + h * 0.62, title, ha="center", va="center",
                fontsize=12, fontweight="bold", color="white", zorder=3)
        ax.text(x + w / 2, y + h * 0.28, sub, ha="center", va="center",
                fontsize=10, color="white", zorder=3)

    box(0.3, 6.4, 2.6, 1.6, "Candidate records", f"{n_cand:,}\n({n_cid:,} normalized CIDs)", "#3a6ea5")
    box(3.5, 6.4, 2.6, 1.6, "Quality triage", f"-{n_miss:,} no freq\n-{n_imag:,} sig. imaginary\n-{n_noconv:,} not converged", "#8a5a9e")
    box(6.7, 6.4, 2.6, 1.6, "Initially qualified", f"{n_qual:,}", TEAL)
    box(6.7, 3.4, 2.6, 1.6, "Grouped dedup", f"-{n_dup:,} qualified duplicates", GOLD)
    box(6.7, 0.5, 2.6, 1.6, "Frozen release", f"{n_rel:,} records", TEAL)

    for x0, y0, x1, y1 in [(2.9, 7.2, 3.5, 7.2), (6.1, 7.2, 6.7, 7.2), (8.0, 6.4, 8.0, 5.0)]:
        ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                    arrowprops=dict(arrowstyle="-|>", color=INK, lw=1.6))
    ax.annotate("", xy=(6.7, 3.4 + 0.0), xytext=(8.0, 5.0 - 0.0),
                xycoords="data", textcoords="data",
                arrowprops=dict(arrowstyle="-|>", color=INK, lw=1.6))

    ax.text(2.0, 9.2, "6,948 - 2,860 - 63 - 13 = 4,012", ha="center", fontsize=10.5, color=INK)
    ax.text(8.0, 5.8, "4,012 - 816 = 3,196", ha="left", fontsize=10.5, color=INK)
    ax.text(0.3, 3.6, "Documented repairs before freeze:\n• 2 formal-charge repairs (CIDs 248, 5571) -> charge +1\n• 1 E/Z stereochemical repair (CID 10946210)",
            fontsize=10, va="top", color="#5a5a5a")

    fig.savefig(FIGDIR / "Fig1_evidence_chain.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Fig1: {n_cand} -> {n_cid} CIDs -> -{n_miss}/-{n_imag}/-{n_noconv} -> {n_qual} -> -{n_dup} -> {n_rel}")


# --------------------------------------------------------------------------- #
# Figure 2 -- chemical space
# --------------------------------------------------------------------------- #
def fig2() -> None:
    df = load_master()

    # (a) element occurrence counts (molecules containing each element)
    elem_counter: Counter = Counter()
    for f in df["molecular_formula"]:
        for el in parse_formula(f):
            elem_counter[el] += 1
    top = elem_counter.most_common(12)
    els = [e for e, _ in top]
    counts = [c for _, c in top]

    mass = _num(df["molecular_mass_amu"])
    xlogp = pd.to_numeric(df["pubchem_XLogP"], errors="coerce")
    tpsa = pd.to_numeric(df["pubchem_TPSA"], errors="coerce")
    comp = pd.to_numeric(df["pubchem_Complexity"], errors="coerce")
    heavy = _num(df["heavy_atom_count"])
    mask_xy = xlogp.notna() & tpsa.notna()

    fig, axes = plt.subplots(2, 2, figsize=(11, 8), dpi=200)

    axes[0, 0].bar(els, counts, color=TEAL, edgecolor="none")
    axes[0, 0].set_ylabel("Molecules containing element")
    axes[0, 0].set_title("(a) Element occurrence", fontweight="bold")

    axes[0, 1].hist(mass, bins=40, color=TEAL, edgecolor="white")
    axes[0, 1].set_xlabel("Molecular mass (amu)")
    axes[0, 1].set_ylabel("Molecule count")
    axes[0, 1].set_title("(b) Molecular-mass distribution", fontweight="bold")

    axes[1, 0].scatter(xlogp[mask_xy], tpsa[mask_xy], s=8, alpha=0.45, color=TEAL)
    axes[1, 0].set_xlabel("PubChem XLogP")
    axes[1, 0].set_ylabel("Topological polar surface area (Å²)")
    axes[1, 0].set_title("(c) XLogP vs TPSA", fontweight="bold")

    axes[1, 1].scatter(heavy, comp, s=8, alpha=0.45, color=GOLD)
    axes[1, 1].set_xlabel("Heavy-atom count")
    axes[1, 1].set_ylabel("PubChem complexity")
    axes[1, 1].set_title("(d) Heavy-atom count vs complexity", fontweight="bold")

    fig.tight_layout()
    fig.savefig(FIGDIR / "Fig2_chemical_space.png", dpi=200)
    plt.close(fig)
    print(f"Fig2: top elements={dict(top[:6])}, mass n={len(mass)}, xlogp/tpsa n={int(mask_xy.sum())}")


# --------------------------------------------------------------------------- #
# Figure 3 -- distributions of representative quantum-chemical properties
# --------------------------------------------------------------------------- #
def fig3() -> None:
    df = load_master()
    panels = [
        ("homo_lumo_gap_ev", "HOMO-LUMO gap (eV)"),
        ("dipole_magnitude_debye", "Dipole magnitude (Debye)"),
        ("zpe_eh", "Zero-point energy (Eh)"),
        ("final_entropy_term_eh", "Entropy term (Eh)"),
        ("lowest_positive_frequency_cm1", "Lowest positive frequency (cm⁻¹)"),
        ("highest_frequency_cm1", "Highest frequency (cm⁻¹)"),
    ]
    fig, axes = plt.subplots(2, 3, figsize=(13, 7.5), dpi=200)
    for ax, (col, label) in zip(axes.flat, panels):
        vals = _num(df[col])
        ax.hist(vals, bins=40, color=TEAL, edgecolor="white")
        ax.axvline(np.median(vals), color=GOLD, linestyle="--", lw=1.4)
        ax.set_xlabel(label)
        ax.set_ylabel("Count")
        ax.set_title(f"{label}\n(n={len(vals):,}, median={np.median(vals):.4g})", fontsize=11, fontweight="bold")
    fig.tight_layout()
    fig.savefig(FIGDIR / "Fig3_quantum_property_atlas.png", dpi=200)
    plt.close(fig)
    med = {col: f"{np.median(_num(df[col])):.4g}" for col, _ in panels}
    print(f"Fig3: medians={med}")


# --------------------------------------------------------------------------- #
# Figure 4 -- technical validation, geometry provenance, exceptions
# --------------------------------------------------------------------------- #
def fig4() -> None:
    df = load_master()
    geo = pd.read_csv(DATA / "audits" / "initial_geometry_pubchem3d_full_results_frozen.csv",
                      encoding="utf-8-sig", dtype={"cid": str})

    n_all = len(df)
    n_term = int(df["normal_termination"].astype(int).sum())
    n_conv = int(df["optimization_converged"].astype(int).sum())
    n_freq = int((df["frequency_count"].astype(int) > 0).sum())
    n_zero_imag = int((df["imaginary_frequency_count"].astype(int) == 0).sum())

    geo_comparable = geo[geo["comparison_status"] == "direct_atom_order"]
    rmsd = pd.to_numeric(geo_comparable["heavy_atom_rmsd_angstrom"], errors="coerce")
    graph_row = geo[geo["cid"] == "10946210"]
    graph_rmsd = float(graph_row["graph_mapping_rmsd_angstrom"].iloc[0]) if len(graph_row) else None

    imag = df[df["imaginary_frequency_count"].astype(int) == 1]
    imag = imag.sort_values("lowest_frequency_cm1")

    fig = plt.figure(figsize=(13, 9), dpi=200)
    gs = fig.add_gridspec(3, 3, hspace=0.55, wspace=0.35)

    ax_a = fig.add_subplot(gs[0, 0])
    checks = ["Normal\ntermination", "Optimization\nconverged", "Frequency\nanalysis", "Zero imaginary\nfrequency"]
    vals = [n_term, n_conv, n_freq, n_zero_imag]
    ax_a.bar(range(4), vals, color=TEAL)
    ax_a.set_xticks(range(4))
    ax_a.set_xticklabels(checks, fontsize=8.5)
    ax_a.set_ylim(0, n_all * 1.12)
    for i, v in enumerate(vals):
        ax_a.text(i, v, f"{v:,}", ha="center", va="bottom", fontsize=9)
    ax_a.set_title("(a) Record-level checks", fontsize=11, fontweight="bold")

    ax_b = fig.add_subplot(gs[0, 1])
    ax_b.barh([2, 1, 0], [len(geo), len(geo_comparable), len(graph_row)],
              color=[TEAL, TEAL, GOLD])
    ax_b.set_yticks([2, 1, 0])
    ax_b.set_yticklabels(["PubChem3D\nretrieved", "Direct atom-order\ncomparable", "Graph-mapped\nrepair"], fontsize=8.5)
    ax_b.set_xlabel("Records")
    ax_b.set_title("(b) Starting-geometry provenance", fontsize=11, fontweight="bold")

    ax_c = fig.add_subplot(gs[0, 2])
    ax_c.hist(rmsd, bins=40, color=TEAL, edgecolor="white")
    if graph_rmsd is not None:
        ax_c.axvline(graph_rmsd, color=GOLD, linestyle="--", lw=1.6)
        ax_c.text(graph_rmsd, ax_c.get_ylim()[1] * 0.9, f"  10946210\n  {graph_rmsd:.3f} Å",
                  color="#8a6d1a", fontsize=8)
    ax_c.set_xlabel("Heavy-atom RMSD (Å)")
    ax_c.set_ylabel("Records")
    ax_c.set_title("(c) RMSD distribution (direct order)", fontsize=11, fontweight="bold")

    ax_d = fig.add_subplot(gs[1, :])
    cids = list(imag["cid"])
    freqs = [float(x) for x in imag["lowest_frequency_cm1"]]
    colors = [GOLD if v < -3.5 else TEAL for v in freqs]
    ax_d.bar(range(len(cids)), freqs, color=colors)
    ax_d.axhline(0, color=INK, lw=1)
    ax_d.set_xticks(range(len(cids)))
    ax_d.set_xticklabels(cids, fontsize=9)
    ax_d.set_ylabel("Signed lowest frequency (cm⁻¹)")
    ax_d.set_title("(d) Five retained minor-negative-mode records", fontsize=11, fontweight="bold")
    for i, v in enumerate(freqs):
        ax_d.text(i, v, f"{v:.2f}", ha="center", va="top" if v < 0 else "bottom", fontsize=8.5)

    ax_e = fig.add_subplot(gs[2, :])
    ax_e.barh([1, 0], [2, 1], color=[TEAL, GOLD])
    ax_e.set_yticks([1, 0])
    ax_e.set_yticklabels(["Formal-charge repair\n(CIDs 248, 5571)", "E/Z stereochemical repair\n(CID 10946210)"], fontsize=9)
    ax_e.set_xlabel("Records")
    ax_e.set_title("(e) Identity and stereochemical repairs", fontsize=11, fontweight="bold")

    fig.savefig(FIGDIR / "Fig4_quality_control.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Fig4: term={n_term} conv={n_conv} freq={n_freq} zero_imag={n_zero_imag}; "
          f"geo comparable={len(geo_comparable)} graph_rmsd={graph_rmsd}; imag={list(zip(cids, freqs))}")


# --------------------------------------------------------------------------- #
# Figure 5 -- ORCA software-version provenance
# --------------------------------------------------------------------------- #
def fig5() -> None:
    df = load_master()
    cnt = df["orca_version"].value_counts()
    v601 = int(cnt.get("6.0.1", 0))
    v611 = int(cnt.get("6.1.1", 0))

    gap = pd.to_numeric(df["homo_lumo_gap_ev"], errors="coerce")
    dip = pd.to_numeric(df["dipole_magnitude_debye"], errors="coerce")
    gap601 = gap[df["orca_version"] == "6.0.1"].to_numpy()
    gap611 = gap[df["orca_version"] == "6.1.1"].to_numpy()
    dip601 = dip[df["orca_version"] == "6.0.1"].to_numpy()
    dip611 = dip[df["orca_version"] == "6.1.1"].to_numpy()

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.2), dpi=200)

    axes[0].bar(["6.0.1", "6.1.1"], [v601, v611], color=[TEAL, GOLD])
    for i, v in enumerate([v601, v611]):
        axes[0].text(i, v, f"{v:,}", ha="center", va="bottom", fontsize=10)
    axes[0].set_ylabel("Records")
    axes[0].set_title("(a) Release counts by version", fontsize=11, fontweight="bold")

    axes[1].hist(gap601, bins=35, alpha=0.6, color=TEAL, label="6.0.1")
    axes[1].hist(gap611, bins=35, alpha=0.6, color=GOLD, label="6.1.1")
    axes[1].set_xlabel("HOMO-LUMO gap (eV)")
    axes[1].set_ylabel("Records")
    axes[1].legend(fontsize=9)
    axes[1].set_title("(b) Orbital-gap distribution", fontsize=11, fontweight="bold")

    axes[2].hist(dip601, bins=35, alpha=0.6, color=TEAL, label="6.0.1")
    axes[2].hist(dip611, bins=35, alpha=0.6, color=GOLD, label="6.1.1")
    axes[2].set_xlabel("Dipole magnitude (Debye)")
    axes[2].set_ylabel("Records")
    axes[2].legend(fontsize=9)
    axes[2].set_title("(c) Dipole-magnitude distribution", fontsize=11, fontweight="bold")

    fig.tight_layout()
    fig.savefig(FIGDIR / "Fig5_software_provenance.png", dpi=200)
    plt.close(fig)
    print(f"Fig5: 6.0.1={v601} 6.1.1={v611}  (sum={v601 + v611})")


# --------------------------------------------------------------------------- #
# Figure 7 -- record-centred release architecture (schematic)
# --------------------------------------------------------------------------- #
def fig7() -> None:
    fig, ax = plt.subplots(figsize=(11, 6.5), dpi=200)
    ax.axis("off")
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 11)

    ax.add_patch(FancyBboxPatch((4.35, 6.4), 3.3, 1.8,
                 boxstyle="round,pad=0.15", facecolor=TEAL, edgecolor="none"))
    ax.text(6.0, 7.35, "PubChem CID", ha="center", va="center", fontsize=14, fontweight="bold", color="white")
    ax.text(6.0, 6.8, "primary join key", ha="center", va="center", fontsize=9, color="white")

    satellites = [
        (0.5, 8.5, "Molecular identity\n(title, formula, SMILES,\nInChI, InChIKey)"),
        (8.7, 8.5, "TCM association\n(TCMSP herb-CID edges,\nconfidence class)"),
        (0.5, 4.5, "Quantum properties\n(energies, orbitals, dipole,\nthermo, vibrational)"),
        (8.7, 4.5, "Optimized geometry\n(one XYZ per CID)"),
        (4.5, 1.4, "Quality metadata\n(flags, warnings, ORCA version)"),
    ]
    for x, y, txt in satellites:
        ax.add_patch(FancyBboxPatch((x, y), 3.0, 1.8,
                     boxstyle="round,pad=0.12", facecolor="#eef3f1", edgecolor=TEAL, linewidth=1.2))
        ax.text(x + 1.5, y + 0.9, txt, ha="center", va="center", fontsize=8.5, color=INK)
        ax.annotate("", xy=(6.0, 7.3), xytext=(x + 1.5, y + 0.9),
                    arrowprops=dict(arrowstyle="-", color=TEAL, lw=1.0, alpha=0.6))

    ax.text(6.0, 10.6, "Citable data layer: checksummed repository files (tables, structures, manifests)",
            ha="center", fontsize=9.5, fontweight="bold", color=INK)
    ax.text(6.0, 0.7, "Discovery layer: website + knowledge graph (search / exploration, not a replacement for versioned artifacts)",
            ha="center", fontsize=9.5, color="#5a5a5a", style="italic")

    fig.savefig(FIGDIR / "Fig7_data_architecture.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("Fig7: architecture schematic (schematic, not data-derived)")


BUILDERS = {"fig1": fig1, "fig2": fig2, "fig3": fig3, "fig4": fig4, "fig5": fig5, "fig7": fig7}


def main() -> None:
    which = sys.argv[1:] or list(BUILDERS)
    for name in which:
        if name not in BUILDERS:
            print(f"unknown figure '{name}' (choose from {', '.join(BUILDERS)})")
            continue
        BUILDERS[name]()


if __name__ == "__main__":
    main()
