/* eslint-disable @next/next/no-html-link-for-pages */
import {notFound} from "next/navigation";
import {getAdjacentCompounds,getCompound,getGlobalPercentile} from "../../lib/data";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
import {MoleculeViewers} from "../../components/MoleculeViewers";

const f=(value:number|null,digits=5)=>value==null?"—":value.toFixed(digits);
const yes=(value:number|null)=>value===1?"是":value===0?"否":"—";
const flag=(value:boolean|number|null|undefined)=>value===true||value===1?"是":value===false||value===0?"否":"—";
const dur=(value:number|null)=>{if(value==null)return "—";if(value<60)return `${value.toFixed(1)} s`;if(value<3600)return `${(value/60).toFixed(1)} min`;return `${(value/3600).toFixed(2)} h`;};
const qc:Record<string,string>={pass:"通过",pass_with_warning:"通过（有提示）",review:"建议复核"};

export default async function Detail({params}:{params:Promise<{cid:string}>}) {
  const {cid}=await params; const x=getCompound(cid); if(!x)notFound();
  const nav=getAdjacentCompounds(cid); const herbs=x.herbNames?x.herbNames.split("|"):[];
  return <><SiteHeader/><main id="main-content" className="detail-page">
    <div className="breadcrumb"><a href="/">首页</a><span>›</span><a href="/#explore">数据探索</a><span>›</span><b>CID {x.cid}</b></div>
    <section className="compound-hero"><div className="compound-formula-art"><span>{x.formula}</span><small>MOLECULAR FORMULA</small></div><div className="compound-title"><p>PubChem CID {x.cid}</p><h1>{x.title||`Compound ${x.cid}`}</h1><div><span>{f(x.molecularWeight,2)} Da</span><span>{x.atomCount} 个原子</span><span>{x.heavyAtomCount} 个重原子</span></div></div><div className={`detail-status ${x.qcStatus}`}><i/><span><small>QUALITY STATUS</small><b>{qc[x.qcStatus]||x.qcStatus}</b></span></div></section>
    <div className="record-layout"><aside className="record-nav"><p>本条记录</p><nav><a href="#structure">分子结构</a><a href="#overview">核心概览</a><a href="#identity">化学身份</a><a href="#electronic">电子结构</a><a href="#thermo">热化学</a><a href="#vibration">振动与质控</a><a href="#source">来源与计算</a></nav><a className="pubchem-link" href={`https://pubchem.ncbi.nlm.nih.gov/compound/${x.cid}`} target="_blank" rel="noreferrer">在 PubChem 查看 →</a>{x.herbCount>0&&<a className="graph-link" href={`/graph?cid=${x.cid}`}>在关系图谱中查看共享药材 →</a>}<a className="xyz-download" href={`/structures/${x.cid}.xyz`} download={`${x.cid}.xyz`}>下载 XYZ 坐标 ↓</a></aside><article className="record-content">
      <Section id="structure" no="01" en="MOLECULAR STRUCTURE" title="二维与三维结构"><MoleculeViewers cid={x.cid} smiles={x.smiles} formula={x.formula}/></Section>
      <Section id="overview" no="02" en="OVERVIEW" title="核心性质概览"><div className="headline-properties"><Metric label="HOMO" value={f(x.homoEv,3)} unit="eV"/><Metric label="LUMO" value={f(x.lumoEv,3)} unit="eV"/><Metric label="HOMO–LUMO 能隙" value={f(x.gapEv,3)} unit="eV" accent/><Metric label="偶极矩" value={f(x.dipoleDebye,3)} unit="Debye"/></div><div className="distribution-strip"><DistributionBar label="HOMO–LUMO 能隙" value={f(x.gapEv,3)} unit="eV" percentile={getGlobalPercentile(x.gapEv,"gapEv")}/><DistributionBar label="偶极矩" value={f(x.dipoleDebye,3)} unit="Debye" percentile={getGlobalPercentile(x.dipoleDebye,"dipoleDebye")}/></div><p className="section-note">同一理论水平下的气相优化与频率结果，适合比较和建模；不等同于实验溶液或固态观测。</p></Section>
      <Section id="identity" no="03" en="CHEMICAL IDENTITY" title="身份与组成"><dl className="definition-grid"><Row k="分子式" v={x.formula}/><Row k="IUPAC 名称" v={x.iupacName||"—"}/><Row k="分子量" v={`${f(x.molecularWeight,5)} g mol⁻¹`}/><Row k="精确质量" v={`${f(x.exactMass,8)} Da`}/><Row k="计算用质量" v={`${f(x.calculatedMassAmu,5)} u`}/><Row k="总电荷 / 多重度" v={`${x.charge} / ${x.multiplicity}`}/><Row k="原子 / 重原子" v={`${x.atomCount} / ${x.heavyAtomCount}`}/><Row k="元素种类" v={String(x.elementCount)}/><Row k="电子数（积分）" v={f(x.electronCount,2)}/><Row k="InChIKey" v={x.inchiKey} wide/><Row k="Canonical SMILES" v={x.smiles} wide/></dl><h3 className="record-subhead">PubChem 分子性质</h3><dl className="definition-grid"><Row k="XLogP" v={f(x.xlogp,2)}/><Row k="拓扑极性表面积 (TPSA)" v={`${f(x.tpsa,2)} Å²`}/><Row k="复杂度" v={f(x.complexity,1)}/><Row k="氢键供体 / 受体" v={`${x.hBondDonorCount} / ${x.hBondAcceptorCount}`}/><Row k="可旋转键" v={String(x.rotatableBondCount)}/></dl></Section>
      <Section id="electronic" no="04" en="ELECTRONIC STRUCTURE" title="电子结构"><div className="energy-diagram"><div><small>OCCUPIED</small><b>HOMO</b><strong>{f(x.homoEv,4)} eV</strong></div><span><b>{f(x.gapEv,4)} eV</b><small>KOHN–SHAM GAP</small></span><div><small>UNOCCUPIED</small><b>LUMO</b><strong>{f(x.lumoEv,4)} eV</strong></div></div><dl className="property-list"><Row k="最终电子能" v={`${f(x.electronicEnergyEh,8)} Eh`}/><Row k="HOMO" v={`${f(x.homoEh,6)} Eh`}/><Row k="LUMO" v={`${f(x.lumoEh,6)} Eh`}/><Row k="能隙" v={`${f(x.gapEh,6)} Eh`}/></dl><h3 className="record-subhead">偶极矩</h3><dl className="property-list"><Row k="偶极矩" v={`${f(x.dipoleDebye,4)} Debye`}/><Row k="偶极矩模" v={`${f(x.dipoleMagnitudeAu,6)} a.u.`}/><Row k="μₓ / μᵧ / μ_z" v={`${f(x.dipoleXAu,4)} / ${f(x.dipoleYAu,4)} / ${f(x.dipoleZAu,4)} a.u.`} wide/></dl><h3 className="record-subhead">前线轨道反应性指标（Koopmans 近似）</h3><dl className="property-list"><Row k="电离能 (IP)" v={`${f(x.koopmansIpEv,4)} eV`}/><Row k="电子亲和能 (EA)" v={`${f(x.koopmansEaEv,4)} eV`}/><Row k="化学势 (μ)" v={`${f(x.chemicalPotentialEv,4)} eV`}/><Row k="电负性 (χ)" v={`${f(x.electronegativityEv,4)} eV`}/><Row k="化学硬度 (η)" v={`${f(x.hardnessEv,4)} eV`}/><Row k="全局软度 (S)" v={`${f(x.softnessEvInv,6)} eV⁻¹`}/><Row k="亲电指数 (ω)" v={`${f(x.electrophilicityEv,4)} eV`}/></dl><p className="caveat">派生量采用前线轨道近似，不应描述为实验电离能、电子亲和能或反应活性证据。</p></Section>
      <Section id="thermo" no="05" en="THERMOCHEMISTRY" title="热化学"><dl className="property-list"><Row k="零点能" v={`${f(x.zpeEh,8)} Eh · ${f(x.zpeKcalMol,3)} kcal mol⁻¹`}/><Row k="总热能" v={`${f(x.totalThermalEnergyEh,8)} Eh`}/><Row k="总焓（298.15 K）" v={`${f(x.enthalpyEh,8)} Eh`}/><Row k="Gibbs 自由能（298.15 K）" v={`${f(x.gibbsEh,8)} Eh`}/></dl><h3 className="record-subhead">热校正（298.15 K）</h3><dl className="property-list"><Row k="振动热校正" v={`${f(x.thermalVibrationalCorrectionEh,8)} Eh`}/><Row k="转动热校正" v={`${f(x.thermalRotationalCorrectionEh,8)} Eh`}/><Row k="平动热校正" v={`${f(x.thermalTranslationalCorrectionEh,8)} Eh`}/><Row k="总热校正" v={`${f(x.totalThermalCorrectionEh,8)} Eh`}/><Row k="焓校正" v={`${f(x.enthalpyCorrectionEh,8)} Eh`}/><Row k="Gibbs 校正" v={`${f(x.gibbsCorrectionEh,8)} Eh`}/></dl><h3 className="record-subhead">熵项 T·S</h3><dl className="property-list"><Row k="电子熵项" v={`${f(x.electronicEntropyTermEh,8)} Eh`}/><Row k="振动熵项" v={`${f(x.vibrationalEntropyTermEh,8)} Eh`}/><Row k="转动熵项" v={`${f(x.rotationalEntropyTermEh,8)} Eh`}/><Row k="平动熵项" v={`${f(x.translationalEntropyTermEh,8)} Eh`}/><Row k="总熵项" v={`${f(x.finalEntropyTermEh,8)} Eh · ${f(x.finalEntropyTermKcalMol,3)} kcal mol⁻¹`}/></dl><p className="caveat">不同元素组成分子的绝对总能不能直接作为稳定性排名。</p></Section>
      <Section id="vibration" no="06" en="VIBRATIONAL QC" title="振动·转动·质控"><div className="headline-properties three"><Metric label="最低频率" value={f(x.lowestFrequencyCm1,2)} unit="cm⁻¹"/><Metric label="最高频率" value={f(x.highestFrequencyCm1,2)} unit="cm⁻¹"/><Metric label="最大 IR 强度" value={f(x.maxIrIntensity,2)} unit="km mol⁻¹"/></div><dl className="property-list"><Row k="最低正频率" v={`${f(x.lowestPositiveFrequencyCm1,2)} cm⁻¹`}/><Row k="频率数量" v={String(x.frequencyCount)}/><Row k="负频率数量" v={String(x.imaginaryCount)}/><Row k="IR 峰数量" v={String(x.irPeakCount)}/></dl><h3 className="record-subhead">转动常数</h3><dl className="property-list"><Row k="A / B / C (cm⁻¹)" v={`${f(x.rotConstACm1,5)} / ${f(x.rotConstBCm1,5)} / ${f(x.rotConstCCm1,5)}`} wide/><Row k="A / B / C (MHz)" v={`${f(x.rotConstAMhz,2)} / ${f(x.rotConstBMhz,2)} / ${f(x.rotConstCMhz,2)}`} wide/></dl><h3 className="record-subhead">质量标记</h3><dl className="property-list"><Row k="数值关系检查" v={yes(x.numericalRelationsPass)}/><Row k="负频率数量" v={String(x.imaginaryCount)}/><Row k="低频率 <20 cm⁻¹" v={flag(x.lowFrequencyLt20)}/><Row k="低频率 <10 cm⁻¹" v={flag(x.lowFrequencyLt10)}/><Row k="微小虚频标记" v={flag(x.tinyImaginaryFrequency)}/><Row k="高警告标记（≥10）" v={flag(x.highWarningCount)}/><Row k="警告数量" v={String(x.warningCount)}/><Row k="复核原因" v={x.reviewReason||"无"}/></dl></Section>
      <Section id="source" no="07" en="PROVENANCE" title="来源与计算"><dl className="definition-grid"><Row k="ORCA 版本" v={x.orcaVersion}/><Row k="基组" v={x.basis||"def2-TZVP"}/><Row k="理论水平" v="B3LYP-D3BJ/def2-TZVP"/><Row k="计算环境" v="气相 · 298.15 K · 1 atm · QRRHO"/><Row k="正常终止 / 优化收敛" v={`${yes(x.normalTermination)} / ${yes(x.optimizationConverged)}`}/><Row k="计算时长" v={dur(x.runtimeSeconds)}/><Row k="方法关键词" v={x.methodKeywords||"—"} wide/><Row k="候选药材关联" v={herbs.length?herbs.join("、"):"当前来源表未映射"} wide/></dl><p className="caveat">候选药材关联只表示来源注释，不代表含量、活性、靶点或临床因果。</p></Section>
    </article></div>
    <nav className="record-pager">{nav.previous?<a href={`/compound/${nav.previous.cid}`}>← 上一条 · CID {nav.previous.cid}</a>:<span/>}<a href="/#explore">返回数据探索</a>{nav.next?<a href={`/compound/${nav.next.cid}`}>CID {nav.next.cid} · 下一条 →</a>:<span/>}</nav>
  </main><SiteFooter/></>;
}

function Section({id,no,en,title,children}:{id:string;no:string;en:string;title:string;children:React.ReactNode}){return <section id={id} className="record-section"><div className="record-section-title"><span>{no}</span><div><small>{en}</small><h2>{title}</h2></div></div>{children}</section>}
function Metric({label,value,unit,accent}:{label:string;value:string;unit:string;accent?:boolean}){return <div className={accent?"accent":""}><small>{label}</small><strong>{value}</strong><span>{unit}</span></div>}
function DistributionBar({label,value,unit,percentile}:{label:string;value:string;unit:string;percentile:number}){return <div className="distribution-bar"><div className="distribution-head"><span>{label}</span><b>{value} {unit}</b><em>全库第 {percentile} 百分位</em></div><div className="distribution-track"><i style={{width:`${Math.max(2,Math.min(100,percentile))}%`}}/></div></div>}
function Row({k,v,wide}:{k:string;v:string;wide?:boolean}){return <div className={wide?"wide":""}><dt>{k}</dt><dd>{v}</dd></div>}
